<div class="friendlyLinks">
    <div class="zjzj-container">
        <div class="section-title">
            <span class="title">友情链接</span>

            <div class="fr">
                <select target="_blank" class="zjzj-select lg" onchange="changeUrl(this)">
                    <option selected="selected">各省工程造价网站</option>
                    <option value="http://www.bjjs.gov.cn/tabid/1815/Default.aspx">北京工程造价网</option>
                    <option value="http://www.shjjw.gov.cn/">上海工程造价网</option>
                    <option value="http://www.jszj.com.cn/">江苏工程造价网</option>
                    <option value="http://www.ahzj.com.cn/">安徽工程造价网</option>
                    <option value="http://www.jxzj.net.cn/">江西工程造价网</option>
                    <option value="http://www.fjgczj.com/">福建工程造价网</option>
                    <option value="http://www.gczj.sd.cn/">山东工程造价网</option>
                    <option value="http://www.hb-cec.com/">河北工程造价网</option>
                    <option value="http://www.lncci.com/">辽宁工程造价网</option>
                    <option value="http://www.gsgczj.com.cn/">甘肃工程造价网</option>
                    <option value="http://www.hbzj.net/">湖北工程造价网</option>
                    <option value="http://www.hnccic.com/">湖南工程造价网</option>
                    <option value="http://www.xjzj.com/">新疆工程造价网</option>
                    <option value="http://www.cqsgczjxx.org/">重庆工程造价网</option>
                    <option value="http://www.tjcac.gov.cn/">天津工程造价网</option>
                    <option value="http://www.gdcost.com/">广东工程造价网</option>
                    <option value="http://www.gxzj.com.cn/">广西工程造价网</option>
                    <option value="http://www.sceci.net/">四川工程造价网</option>
                    <option value="http://www.qssoft.com.cn/">吉林工程造价网</option>
                    <option value="http://www.szcost.cn/">深圳工程造价网</option>
                    <option value="http://www.yncost.com/">云南造价信息网</option>
                </select>

                <select target="_blank" class="zjzj-select lg" onchange="changeUrl(this)">
                    <option selected="selected">相关链接</option>
                    <option value="http://www.mohurd.gov.cn/">中华人民共和国住房和城乡建设部</option>
                    <option value="http://www.zhaobiao.gov.cn/">中国建设招标网</option>
                    <option value="http://www.cecn.gov.cn/">中国工程建设信息网</option>
                    <option value="http://www.build.com.cn/">中国建设科技网</option>
                    <option value="http://www.vertinfo.com/archionline/">中国建筑业在线</option>
                    <option value="http://www.zjjs.com.cn/">浙江省建设信息港</option>
                </select>
            </div>

        </div>

        <div class="section-content tc">
            <ul class="friendly-link-ul clearfix inline-block">
                <li>
                    <a href="http://www.ceca.org.cn/" target="_blank">
                        <img src="/static/images/friend/zgjsgczjglxh.jpg" width="138" height="33" alt="中国建设工程造化管理协会">
                    </a>
                </li>
                <li>
                    <a href="http://www.zjzj.net" target="_blank">
                        <img src="/static/images/friend/zjzj.jpg" width="138" height="33" alt="浙江造价">
                    </a>
                </li>

                <li>
                    <a href="http://www.zjjs.com.cn/" target="_blank">
                        <img src="/static/images/friend/zjjs.jpg" width="138" height="33" alt="浙江建设">
                    </a>
                </li>
                <li>
                    <a href="http://www.pinming.cn/" target="_blank">
                        <img src="/static/images/friend/pms.png" width="138" height="33" alt="品茗">
                    </a>
                </li>


                <!--<li>-->
                    <!--<a href="http://www.mohurd.gov.cn/" target="_blank">-->
                        <!--<img src="/static/images/link_1.jpg" width="145" height="42" alt="中华人民共和国住房和城乡建设部">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li>-->
                    <!--<a href="http://www.zj.gov.cn/" target="_blank">-->
                        <!--<img src="/static/images/link_zj_gov_blue.jpg" width="145" height="42" alt="浙江省人民政府">-->
                    <!--</a>-->
                <!--</li>-->

                <!--<li>-->
                    <!--<a href="http://www.cecn.gov.cn" target="_blank">-->
                        <!--<img src="/static/images/zgzjxxw.jpg" width="145" height="42" alt="中国建设工程造价信息网">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li>-->
                    <!--<a href="http://www.ceca.org.cn/" target="_blank">-->
                        <!--<img src="/static/images/link_3.jpg" width="145" height="42" alt="中国建设工程造价管理协会">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li>-->
                    <!--<a href="http://www.ccost.com" target="_blank">-->
                        <!--<img src="/static/images/link_2.jpg" width="145" height="42" alt="工程造价信息网">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li class="last">-->
                    <!--<a href="http://www.zjzjxh.com/Index.asp" target="_blank">-->
                        <!--<img src="/static/images/zjzjxh.jpg" width="145" height="42" alt="浙江省建设工程造价管理协会"></a>-->
                <!--</li>-->

                <!--<li>-->
                    <!--<a href="http://www.zjjs.gov.cn" target="_blank">-->
                        <!--<img src="/static/images/link_4.jpg" width="145" height="42" alt="浙江建设">-->
                    <!--</a>-->
                <!--</li>-->

                <!--<li>-->
                    <!--<a href="http://www.zjdpc.gov.cn" target="_blank">-->
                        <!--<img src="/static/images/link_5.jpg" width="145" height="42" alt="浙江省发展和改革委员会">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li>-->
                    <!--<a href="http://www.zjczt.gov.cn" target="_blank">-->
                        <!--<img src="/static/images/link_6.jpg" width="145" height="42" alt="浙江省财政厅">-->
                    <!--</a>-->
                <!--</li>-->
                <!--<li>-->
                    <!--<a href="http://www.zjsjt.gov.cn" target="_blank">-->
                        <!--<img src="/static/images/link_7.jpg" width="145" height="42" alt="浙江审计">-->
                    <!--</a>-->
                <!--</li>-->


                <!--<li>-->
                    <!--<a href="http://www.pinming.cn/" target="_blank">-->
                        <!--<img src="/static/images/newtheme/zjjcgl2.png" width="145" height="42" alt="浙江省建材价格采集管理系统">-->
                    <!--</a>-->
                <!--</li>-->

                <!--<li class="last">-->
                    <!--<a href="http://www.qzhsoft.com/home.php" target="_blank">-->
                        <!--<img src="/static/images/qzsoft.jpg" width="145" height="42" alt="擎洲软件">-->
                    <!--</a>-->
                <!--</li>-->
            </ul>
        </div>
    </div>
</div>