<!-- 页头 -->
<div class="_zjzj-header clearfix">
    <!--<div class="header-toolbar">-->
        <!--<div class="zjzj-container clearfix">-->

            <!--<div class="tool fl">-->
                <!--<span class="cursor" id="set_as_homepage">设为首页</span> <span class="zjzj-seperator">|</span> <span-->
                    <!--class="cursor" id="add_to_favorite">加入收藏</span>-->
            <!--</div>-->

            <!--&lt;!&ndash;<div class="weather fr clearfix">&ndash;&gt;-->
            <!--&lt;!&ndash;<ul class="tianqi fl">&ndash;&gt;-->
            <!--&lt;!&ndash;<li id="curr_date_tip" class="curr-date"></li>&ndash;&gt;-->
            <!--&lt;!&ndash;<li class="weather-info"><iframe allowtransparency="true" frameborder="0" width="260" height="28" scrolling="no" src="http://tianqi.2345.com/plugin/widget/index.htm?s=3&amp;z=1&amp;t=0&amp;v=0&amp;d=1&amp;bd=0&amp;k=&amp;f=&amp;q=1&amp;e=1&amp;a=1&amp;c=58457&amp;w=317&amp;h=28&amp;align=center"></iframe></li>&ndash;&gt;-->
            <!--&lt;!&ndash;</ul>&ndash;&gt;-->
            <!--&lt;!&ndash;</div>&ndash;&gt;-->

        <!--</div>-->
    <!--</div>-->

    <div class="headerBanner">
        <div class="container clearfix">

            <img class="headerBanner__logo" src="/static/images/logo.png" alt="">

            <!--<span class="headerBanner__name">金华市建设工程造价管理协会</span>-->

            <div class="fr mt-50">
                <div class="weather clearfix">
                    <ul class="tianqi fl">
                        <li id="curr_date_tip" class="curr-date"></li>
                        <li class="weather-info"><iframe allowtransparency="true" frameborder="0" width="260" height="28" scrolling="no" src="http://tianqi.2345.com/plugin/widget/index.htm?s=3&amp;z=1&amp;t=0&amp;v=0&amp;d=1&amp;bd=0&amp;k=&amp;f=&amp;q=1&amp;e=1&amp;a=1&amp;c=58457&amp;w=317&amp;h=28&amp;align=center"></iframe></li>
                    </ul>
                </div>

                <div class="searchToolbar">
                    <form id="all_site_form" action="/search/allSite">

                        <div class="zjzj-search">
                            <div id="all_site_glass" class="zjzj-search-glass"></div>
                            <input id="all_site_search" class="zjzj-input" name="content" type="text" placeholder="请输入关键字">
                        </div>

                    </form>
                </div>

                <!--<div class="noticeTip">-->
                    <!--<div class="noticeTip__box">-->
                        <!--<ul id="notice_tip_line" class="noticeTip__line">-->
                            <!--<li class="noticeTip__line&#45;&#45;item"><a href="#">新闻1xxxxxxx</a></li>-->
                            <!--<li class="noticeTip__line&#45;&#45;item"><a href="#">新闻2yyyyyyy</a></li>-->
                            <!--<li class="noticeTip__line&#45;&#45;item"><a href="#">新闻3</a></li>-->
                            <!--<li class="noticeTip__line&#45;&#45;item"><a href="#">新闻4</a></li>-->
                        <!--</ul>-->
                    <!--</div>-->
                <!--</div>-->
            </div>

        </div>
    </div>



    <div class="header-navbar">
        <div class="zjzj-container clearfix">
            <a href="/index">
                <div class="navbar-item fl">首页</div>
            </a>

            <div class="navbar-seperator fl"></div>
            <div class="navbar-item fl">协会介绍
                <div class="sub-menu">
                    <a href="#">协会简介</a>
                    <a href="#">协会章程</a>
                    <a href="#">组织架构</a>
                    <a href="#">联系方式</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>

            <div class="navbar-seperator fl "></div>
            <div class="navbar-item fl hover">政策法规
                <div class="sub-menu">
                    <a href="#">政策</a>
                    <a href="#">法规</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>

            <div class="navbar-seperator fl "></div>
            <div class="navbar-item fl">学术探讨
                <div class="sub-menu">
                    <a href="#">学术</a>
                    <a href="#">探讨</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>

            <div class="navbar-seperator fl "></div>
            <div class="navbar-item fl">会员风采
                <div class="sub-menu">
                    <a href="#">会员名录</a>
                    <a href="#">会员展示</a>
                    <a href="#">会员活动</a>
                    <a href="#">会员荣誉</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>


            <div class="navbar-seperator fl "></div>
            <div class="navbar-item fl">党建园地
                <div class="sub-menu">
                    <a href="#">党建</a>
                    <a href="#">园地</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>

            <div class="navbar-seperator fl "></div>
            <div class="navbar-item fl">服务指南
                <div class="sub-menu">
                    <a href="#">入会流程</a>
                    <a href="#">刊登价格信息流程</a>
                    <a href="#">工作群介绍</a>

                    <iframe id='iframebar' src="about:blank" frameBorder=0 marginHeight=0 marginWidth=0
                            style="position:absolute; visibility:inherit; top:0px;left:0px;height:100%;width:100%; z-Index:-1; filter='progid:DXImageTransform.Microsoft.Alpha(style=0,opacity=0)';">
                    </iframe>
                </div>
            </div>

        </div>
    </div>
</div>