<!-- 页尾 -->
<div class="_zjzj-footer zjzjFooter">
    <div class="zjzj-container">
        <div class="zjzjFooter__bar footer-nav">
            <a href="#">关于我们</a>
            <span class="zjzj-seperator">|</span>
            <a href="mailto:zjzjzz@vip.126.com">联系我们</a>
            <span class="zjzj-seperator">|</span>
            <a href="#">网站导航</a>
            <!--<span class="zjzj-seperator">|</span>-->
            <!--<a href="#">会员注册</a>-->
        </div>

        <!--号 -->
        <!---->


        <div class="zjzjFooter__bar support-txt">
            <p class="zjzjFooter__bar--item">
                CopyRight©2018 金华市建设工程造价管理协会官方网站  版权所有
            </p>
            <p class="zjzjFooter__bar--item">
                技术支持：杭州品茗安控信息技术股份有限公司
            </p>

            <p class="zjzjFooter__bar--item copyright-txt">
                浙公网安备
                <a style="color:#666;" href="#" target="_blank">浙ICP备 8888888号</a>
            </p>

        </div>
    </div>
</div>